config/routes.rb
Rails.application.routes.draw do

  get  '/convert/:clip_id' => 'convert#perform', as: :convert
  get  '/process' => 'convert#process', as: :process

  resources :users

  resources :clips

  resources :episodes

  resources :shows

  root 'episodes#index'
  
  get '/embed' => 'static#embed'

  get '/proxy' => 'static#proxy', as: :proxy

end

app/models/clip.rb
class Clip < ActiveRecord::Base
	belongs_to :episode
	belongs_to :user

	def to_param
		#{}"#{id}-#{name.parameterize}"
		["#{id}", "#{user.try(:name).parameterize}", "#{episode.try(:name).parameterize}"].join("-")
	rescue
		"#{id}"
	end

	def get_image_url
		self.episode.try(:image_url)
	end

	def og_title
		""
	end

	def og_desc
		""
	end


end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
  before_action :set_clip, only: [:show, :edit, :update, :destroy]

  # GET /clips
  # GET /clips.json
  def index
    if params[:episode_id].present?
      @clips = Clip.where(episode: Episode.find(params[:episode_id])).all
    else
      @clips = Clip.all
    end
  end

  # GET /clips/1
  # GET /clips/1.json
  def show
  end

  # GET /clips/new
  def new
    @clip = Clip.new
    if params[:episode_id].present?
      @clip.episode_id = params[:episode_id]
    end
  end

  # GET /clips/1/edit
  def edit
  end

  # POST /clips
  # POST /clips.json
  def create
    @clip = Clip.new(clip_params)

    respond_to do |format|
      if @clip.save
        format.html { redirect_to @clip, notice: 'Clip was successfully created.' }
        format.json { render :show, status: :created, location: @clip }
      else
        format.html { render :new }
        format.json { render json: @clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clips/1
  # PATCH/PUT /clips/1.json
  def update
    respond_to do |format|
      if @clip.update(clip_params)
        format.html { redirect_to @clip, notice: 'Clip was successfully updated.' }
        format.json { render :show, status: :ok, location: @clip }
      else
        format.html { render :edit }
        format.json { render json: @clip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clips/1
  # DELETE /clips/1.json
  def destroy
    @clip.destroy
    respond_to do |format|
      format.html { redirect_to clips_url, notice: 'Clip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clip
      @clip = Clip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clip_params
      params.require(:clip).permit(:user_id, :episode_id, :start_time, :duration, :image_url, :message)
    end
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/views/clips/_form.html.erb
<%= form_for(@clip) do |f| %>
  <% if @clip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clip.errors.count, "error") %> prohibited this clip from being saved:</h2>

      <ul>
      <% @clip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :episode_id %><br>
    <%= f.collection_select(:episode_id, Episode.all, :id, :name, prompt: true) %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message, cols: 50, rows: 2, style: 'font-size:20px' %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select(:user_id, User.all, :id, :name, prompt: true) %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.text_field :start_time %>
  </div>

  <% if @clip.episode.present? %>
    <audio id="audioplayer" src="<%= @clip.episode.audio_url %>" controls style="width:100%;"></audio>
    <script>
    (function() {
      var el = document.querySelector('#audioplayer');
      setInterval(function() {
        var t = el.currentTime;
        if (!el.paused) {
          // t = parseInt(t, 10);
          $('#clip_start_time').val(t);          
        }
      }, 500);
    })();
    </script>
  <% end %>
  
  <!-- <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </div> -->

<!--   <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_area :image_url %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clips/edit.html.erb
<article class="content">


<h1>Editing Clip</h1>

<%= render 'form' %>

<%= link_to 'Show', @clip %> |
<%= link_to 'Back', clips_path %>

<%= link_to "Edit Episode", edit_episode_path(id: @clip.episode.try(:id)) %>
</article>

app/views/clips/index.html.erb
<h1>Listing clips</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>User</th>
      <th>Episode</th>
      <th>Start time</th>
      <th>Duration</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clips.each do |clip| %>
      <tr>
        <td><%= clip.user_id %></td>
        <td><%= clip.episode_id %></td>
        <td><%= clip.start_time %></td>
        <td><%= clip.duration %></td>
        <td><%= clip.image_url %></td>
        <td><%= link_to 'Show', clip %></td>
        <td><%= link_to 'Edit', edit_clip_path(clip) %></td>
        <td><%= link_to 'Destroy', clip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clip', new_clip_path %>

app/views/clips/new.html.erb
<article class="content">

<h1>New clip</h1>

<%= render 'form' %>

<%= link_to 'Back', clips_path %>
</article>

app/views/clips/show.html.erb
<% content_for(:head) do %>

<meta property="og:site_name" content="soundszr">
<meta property="og:url" content="<%= clip_url @clip %>">
<meta property="og:title" content="<%= @clip.og_title %>">
<meta property="og:description" content="<%= @clip.og_desc %>">
<meta property="og:image" content="<%= @clip.get_image_url %>">
<meta property="og:type" content="video">
<meta property="og:video:url" content="<%= @clip.video_url %>">
<meta property="og:video:secure_url" content="<%= @clip.video_url %>">
<meta property="og:video:type" content="video/mp4">
<meta property="og:video:width" content="1280">
<meta property="og:video:height" content="720">

<% end %>

      <section class="szrblock">
        <%= image_tag proxy_path(url: @clip.try(:episode).try(:image_url)), style: 'max-width: 150px;' %>
        
        <article id="szr-id">
          <h1><%= @clip.try(:episode).try(:show).try(:name) %></h1>
          <h3><%= @clip.try(:episode).try(:name) %></h3>
          <p><%= @clip.try(:episode).try(:description) %></p>
          
          <audio></audio>

        </article>
        <div class="clear"></div>
      </section>
    
      <section id="message-id" class="message">
        <h3>Message</h3>
        <p>“<%= @clip.message %>”</p>
        <p>~<%= @clip.user.try(:name) %></p>
        <%= link_to 'Edit', edit_clip_path(@clip) %>
        <div class="clear"></div>
      </section>
    
      <div class="buttons">
        <%= link_to @clip.episode.episode_url do %><button class="full red">Full Episode</button><% end %>
        <a href="#" onClick="fbShare()">
          <button class="share red">Share <i class="fa fa-facebook-official"></i></button>
        </a>
        <div class="clear"></div>
      </div>
      
      
   
<script>
(function() {  
  $.ajax({
    type: "GET",
    url: '/process',
    data: {
      clip_id: <%= @clip.id %>
    },
    success: function(data) {
      console.log(data)
    },
  });
})();

  function fbShare() {    
      var title = "Share soundszr";
      var descr = "Share soundszr desc";
      var url = "<%= clip_url(@clip) %>";
      var winHeight = 330;
      var winWidth = 450;

      var winTop = (screen.height / 2) - (winHeight / 2);
      var winLeft = (screen.width / 2) - (winWidth / 2);
      window.open('http://www.facebook.com/sharer.php?s=100&p[title]=' + title + '&p[summary]=' + descr + '&p[url]=' + url, 'sharer', 'top=' + winTop + ',left=' + winLeft + ',toolbar=0,status=0,width=' + winWidth + ',height=' + winHeight);
  }
</script>