config/routes.rb
Rails.application.routes.draw do

  get  '/convert/:clip_id' => 'convert#perform', as: :convert
  get  '/process' => 'convert#process', as: :process

  resources :users

  resources :clips

  resources :episodes

  resources :shows

  root 'episodes#index'
  
  get '/embed' => 'static#embed'

  get '/proxy' => 'static#proxy', as: :proxy

end

app/models/episode.rb
class Episode < ActiveRecord::Base
	belongs_to :show
	has_many :clips

	def to_param
		"#{id}-#{name.parameterize}"
	end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy]

  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.all
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
  end

  # POST /episodes
  # POST /episodes.json
  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, notice: 'Episode was successfully created.' }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1
  # PATCH/PUT /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to @episode, notice: 'Episode was successfully updated.' }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to episodes_url, notice: 'Episode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:show_id, :name, :description, :image_url, :audio_url, :episode_url)
    end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_form.html.erb
<article class="content">
		<%= form_for(@episode) do |f| %>
	  <% if @episode.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@episode.errors.count, "error") %> prohibited this episode from being saved:</h2>
	
	      <ul>
	      <% @episode.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	
	  <div class="field">
	    <%= f.label :show_id %><br>
	    <%= f.collection_select(:show_id, Show.all, :id, :name, prompt: true) %>
	  </div>
	  <div class="field">
	    <%= f.label :name %><br>
	    <%= f.text_area :name, cols: 80, rows: 3  %>
	  </div>
	  <div class="field">
	    <%= f.label :description %><br>
	    <%= f.text_area :description, cols: 80 %>
	  </div>
	  <div class="field">
	    <%= f.label :image_url %><br>
	    <%= f.text_area :image_url, cols: 80  %>
	  </div>
	  <div class="field">
	    <%= f.label :audio_url %><br>
	    <%= f.text_area :audio_url, cols: 80  %>
	  </div>
	  <div class="field">
	    <%= f.label :episode_url %><br>
	    <%= f.text_area :episode_url, cols: 80  %>
	  </div>
	  <div class="actions">
	    <%= f.submit %>
	  </div>
	<% end %>
</article>

app/views/episodes/edit.html.erb
<article class="content">
	<h1>Editing episode</h1>

	<%= render 'form' %>
	
	<%= link_to 'Show', @episode %> |
	<%= link_to 'Back', episodes_path %>
</article>

app/views/episodes/index.html.erb
<section class="home">
	<h1>Welcome to soundszr</h1>
	<p>On soundszr, listeners can select and share moments of their favorite podcasts with their favorite people on Facebook.</p>	
	
</section>

<article class="content">
	<h1>Episodes</h1>
	
	<table class="table table-striped">
	  <thead>
	    <tr>	      
	      <th></th>
	      <th>Show</th>
	      <th>Name</th>
	      <th>Description</th>
	      <th colspan="3"></th>
	    </tr>
	  </thead>
	
	  <tbody>
	    <% @episodes.each do |episode| %>
	      <tr>	        	        
	        <td><%= image_tag proxy_path(url: episode.image_url) %></td>
	        <td><%= episode.show.try(:name) %></td>
	        <td><%= episode.name %></td>
	        <td>
	        	<%= episode.description %><br>
	        	<br>
	        	<%= link_to "Create A Clip", new_clip_path(episode_id: episode.id) %><br>
	        	<%= link_to "Browse Clips", clips_path(episode_id: episode.id) %>
	        </td>
	        <td><%= link_to 'Show', episode %></td>
	        <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
	        <!-- <td><%= link_to 'Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
	      </tr>
	    <% end %>
	  </tbody>
	</table>
	
	<br>
	
	<%= link_to 'New Episode', new_episode_path %>
</article>

app/views/episodes/new.html.erb
<article class="content">
	<h1>New episode</h1>

	<%= render 'form' %>
	
	<%= link_to 'Back', episodes_path %>
</article>

app/views/episodes/show.html.erb
<article class="content">
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Show:</strong>
	  <%= @episode.show_id %>
	</p>
	
	<p>
	  <strong>Name:</strong>
	  <%= @episode.name %>
	</p>
	
	<p>
	  <strong>Description:</strong>
	  <%= @episode.description %>
	</p>
	
	<p>
	  <strong>Image url:</strong>
	  <%= @episode.image_url %>
	</p>
	
	<p>
	  <strong>Audio url:</strong>
	  <%= @episode.audio_url %>
	</p>
	
	<%= link_to 'Edit', edit_episode_path(@episode) %> |
	<%= link_to 'Back', episodes_path %>
</article>