config/routes.rb
Rails.application.routes.draw do

  get  '/convert/:clip_id' => 'convert#perform', as: :convert
  get  '/process' => 'convert#process', as: :process

  resources :users

  resources :clips

  resources :episodes

  resources :shows

  root 'episodes#index'
  
  get '/embed' => 'static#embed'

  get '/proxy' => 'static#proxy', as: :proxy

end

app/models/show.rb
class Show < ActiveRecord::Base
	def to_param
		"#{id}-#{name.parameterize}"
	end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :edit, :update, :destroy]

  # GET /shows
  # GET /shows.json
  def index
    @shows = Show.all
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to @show, notice: 'Show was successfully created.' }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1
  # PATCH/PUT /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show.destroy
    respond_to do |format|
      format.html { redirect_to shows_url, notice: 'Show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def show_params
      params.require(:show).permit(:name, :description, :distributor)
    end
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/shows/_form.html.erb
<article class="content">
	<%= form_for(@show) do |f| %>
	  <% if @show.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@show.errors.count, "error") %> prohibited this show from being saved:</h2>
	
	      <ul>
	      <% @show.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	
	  <div class="field">
	    <%= f.label :name %><br>
	    <%= f.text_area :name %>
	  </div>
	  <div class="field">
	    <%= f.label :description %><br>
	    <%= f.text_area :description %>
	  </div>
	  <div class="field">
	    <%= f.label :distributor %><br>
	    <%= f.text_area :distributor %>
	  </div>
	  <div class="actions">
	    <%= f.submit %>
	  </div>
	<% end %>
</article>

app/views/shows/edit.html.erb
<article class="content">
	<h1>Editing show</h1>

	<%= render 'form' %>
	
	<%= link_to 'Show', @show %> |
	<%= link_to 'Back', shows_path %>
</article>

app/views/shows/index.html.erb
<article class="content">
	<h1>Listing shows</h1>

	<table class="table table-striped">
	  <thead>
	    <tr>
	      <th>Name</th>
	      <th>Description</th>
	      <th>Distributor</th>
	      <th colspan="3"></th>
	    </tr>
	  </thead>
	
	  <tbody>
	    <% @shows.each do |show| %>
	      <tr>
	        <td><%= show.name %></td>
	        <td><%= show.description %></td>
	        <td><%= show.distributor %></td>
	        <td><%= link_to 'Show', show %></td>
	        <td><%= link_to 'Edit', edit_show_path(show) %></td>
	        <td><%= link_to 'Destroy', show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
	
	<br>
	
	<%= link_to 'New Show', new_show_path %>
</article>

app/views/shows/new.html.erb
<article class="content">
	<h1>New show</h1>
	
	<%= render 'form' %>
	
	<%= link_to 'Back', shows_path %>
</article>

app/views/shows/show.html.erb
<article class="content">
	<p id="notice"><%= notice %></p>
	
	<p>
	  <strong>Name:</strong>
	  <%= @show.name %>
	</p>
	
	<p>
	  <strong>Description:</strong>
	  <%= @show.description %>
	</p>
	
	<p>
	  <strong>Distributor:</strong>
	  <%= @show.distributor %>
	</p>
	
	<%= link_to 'Edit', edit_show_path(@show) %> |
	<%= link_to 'Back', shows_path %>
</article>